/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7android8hardware3drm4V1_216BpHwCryptoPlugin11decrypt_1_2EbRKNS0_10hidl_arrayIhLm16EJEEES7_NS1_4V1_04ModeERKNS8_7PatternERKNS0_8hidl_vecINS8_9SubSampleEEERKNS8_12SharedBufferEmRKNS8_17DestinationBufferENSt3__18functionIFvNS2_6StatusEjRKNS0_11hidl_stringEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call _ZN7android8hardware3drm4V1_216BpHwCryptoPlugin11decrypt_1_2EbRKNS0_10hidl_arrayIhLm16EJEEES7_NS1_4V1_04ModeERKNS8_7PatternERKNS0_8hidl_vecINS8_9SubSampleEEERKNS8_12SharedBufferEmRKNS8_17DestinationBufferENSt3__18functionIFvNS2_6StatusEjRKNS0_11hidl_stringEEEE.
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter(log, args, state) {
    log('_ZN7android8hardware3drm4V1_216BpHwCryptoPlugin11decrypt_1_2EbRKNS0_10hidl_arrayIhLm16EJEEES7_NS1_4V1_04ModeERKNS8_7PatternERKNS0_8hidl_vecINS8_9SubSampleEEERKNS8_12SharedBufferEmRKNS8_17DestinationBufferENSt3__18functionIFvNS2_6StatusEjRKNS0_11hidl_stringEEEE()');
  },

  /**
   * Called synchronously when about to return from _ZN7android8hardware3drm4V1_216BpHwCryptoPlugin11decrypt_1_2EbRKNS0_10hidl_arrayIhLm16EJEEES7_NS1_4V1_04ModeERKNS8_7PatternERKNS0_8hidl_vecINS8_9SubSampleEEERKNS8_12SharedBufferEmRKNS8_17DestinationBufferENSt3__18functionIFvNS2_6StatusEjRKNS0_11hidl_stringEEEE.
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave(log, retval, state) {
  }
}
